sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  #阿里云OSS
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tNzP2YuQVExgsYuG3Vb
    access-key-secret: 87BwJFQPussUwDWp3uKRRrj0ALRDKU
    bucket-name: web777

#Redis配置
spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0